apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  selector:
    app: elasticsearch
  ports:
  - port: {{ .Values.elasticsearch.service.port }}
    name: http
    targetPort: {{ .Values.elasticsearch.service.port }}
  - port: {{ .Values.elasticsearch.service.transportPort }}
    name: transport
    targetPort: {{ .Values.elasticsearch.service.transportPort }}
  type: {{ .Values.elasticsearch.service.type }}
